# Imagen base de Node.js
FROM node:22-bullseye

# Directorio de trabajo dentro del contenedor
WORKDIR /app-node

# Copiamos primero los archivos de dependencias para aprovechar la cache de Docker
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del código de la aplicación
COPY . .

# Exponemos el puerto del backend
EXPOSE 3000

# Comando por defecto (modo desarrollo con nodemon)
CMD ["npm", "run", "dev"]
